name: Run Bond Pricing Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Runs nightly at 2 AM UTC
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 🧪 Install dependencies
        run: |
          pip install pytest

      - name: 🚀 Run tests
        run: |
          pytest Test_Bond_Pricing.py

      - name: 🗂️ Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: fuzzing-logs
          path: bond_fuzzing.log